server:
  port: 9991
spring:
  profiles:
    active: dev
  application:
    name: construct
#logging:
#  config: classpath:logback-spring.xml
#
#
#mybatis:
#  mapper-locations: classpath:mappers/*.xml
#  configuration:
#    map-underscore-to-camel-case: true




